version: "3.8"

services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: TZ
        value: Asia/Ho_Chi_Minh
  
